#include "dxfw-tests.h"

int main() {
  const struct CMUnitTest tests[] = {
    cmocka_unit_test(dxfwInitTest),
    cmocka_unit_test(dxfwDoubleInitTest),
    cmocka_unit_test(dxfwNoInitTest),
    cmocka_unit_test(dxfwMemoryTest),
    cmocka_unit_test(dxfwSetAllocNullArguments),
    cmocka_unit_test_setup_teardown(dxfwNotInitializedTest, dxfwNotInitializedTestSetup, dxfwNotInitializedTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwGetTimeTest, dxfwInitializedTestSetup, dxfwInitializedTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwCreateDestroyWindowTest, dxfwInitializedTestSetup, dxfwInitializedTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwCreateWindowWithZeroWidthTest, dxfwInitializedTestSetup, dxfwInitializedTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwCreateWindowWithZeroHeightTest, dxfwInitializedTestSetup, dxfwInitializedTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwCreateWindowWithEmptyTitleTest, dxfwInitializedTestSetup, dxfwInitializedTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwCreateWindowWithNullTitleTest, dxfwInitializedTestSetup, dxfwInitializedTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwDestroyNullWindowTest, dxfwInitializedTestSetup, dxfwInitializedTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwGetHandleTest, dxfwSingleWindowTestSetup, dxfwSingleWindowTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwGetHandleForNullTest, dxfwInitializedTestSetup, dxfwInitializedTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwSetAndGetUserDataTest, dxfwSingleWindowTestSetup, dxfwSingleWindowTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwSetNullWindowUserData, dxfwInitializedTestSetup, dxfwInitializedTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwGetNullWindowUserData, dxfwInitializedTestSetup, dxfwInitializedTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwSetWindowCaptionTest, dxfwInitializedTestSetup, dxfwInitializedTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwSetEmptyWindowCaptionTest, dxfwInitializedTestSetup, dxfwInitializedTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwSetNullWindowCaptionTest, dxfwInitializedTestSetup, dxfwInitializedTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwSetWindowNullCaptionTest, dxfwSingleWindowTestSetup, dxfwSingleWindowTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwGetWindowSizeTest, dxfwSingleWindowTestSetup, dxfwSingleWindowTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwGetWindowSizeNullWindowTest, dxfwInitializedTestSetup, dxfwInitializedTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwGetWindowSizeNullWidthTest, dxfwSingleWindowTestSetup, dxfwSingleWindowTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwGetWindowSizeNullHeightTest, dxfwSingleWindowTestSetup, dxfwSingleWindowTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwSetWindowSizeTest, dxfwSingleWindowTestSetup, dxfwSingleWindowTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwSetWindowSizeToZeroWidthTest, dxfwSingleWindowTestSetup, dxfwSingleWindowTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwSetWindowSizeToZeroHeightTest, dxfwSingleWindowTestSetup, dxfwSingleWindowTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwSetNullWindowSizeTest, dxfwInitializedTestSetup, dxfwInitializedTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwShouldWindowCloseTest, dxfwSingleWindowTestSetup, dxfwSingleWindowTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwShouldWindowCloseNullWindowTest, dxfwInitializedTestSetup, dxfwInitializedTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwShouldCloseChangedCallbackNullWindowTest, dxfwInitializedTestSetup, dxfwInitializedTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwPollOsEventsTest, dxfwSingleWindowTestSetup, dxfwSingleWindowTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwTwoWindowTest, dxfwInitializedTestSetup, dxfwInitializedTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwGetKeyStateTest, dxfwSingleWindowTestSetup, dxfwSingleWindowTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwGetModifierFlagsTest, dxfwSingleWindowTestSetup, dxfwSingleWindowTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwKeyboardCallbackTest, dxfwSingleWindowTestSetup, dxfwSingleWindowTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwKeyboardCallbackNullWindowTest, dxfwInitializedTestSetup, dxfwInitializedTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwSetMouseButtonCallbackTest, dxfwSingleWindowTestSetup, dxfwSingleWindowTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwSetMouseButtonCallbackNullWindowTest, dxfwInitializedTestSetup, dxfwInitializedTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwSetMouseMoveCallbackTest, dxfwSingleWindowTestSetup, dxfwSingleWindowTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwSetMouseMoveCallbackNullWindowTest, dxfwInitializedTestSetup, dxfwInitializedTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwSetMouseWheelCallbackTest, dxfwSingleWindowTestSetup, dxfwSingleWindowTestTeardown),
    cmocka_unit_test_setup_teardown(dxfwSetMouseWheelCallbackNullWindowTest, dxfwSingleWindowTestSetup, dxfwSingleWindowTestTeardown),
  };

  return cmocka_run_group_tests(tests, NULL, NULL);
}
