#include "dxfw/dxfw.h"
#include "dxfw_internal.h"

/* KEY TRANSLATION TABLE */
dxfwVirtualKeyCode g_windows_to_virtual_key_code_[256] = {
  /* 0x00, NONE */ DXFW_KEY_NONE,
  /* 0x01, LEFT_MOUSE_BUTTON */ DXFW_KEY_NONE,
  /* 0x02, RIGHT_MOUSE_BUTTON */ DXFW_KEY_NONE,
  /* 0x03, CANCEL */ DXFW_KEY_NONE,
  /* 0x04, MIDDLE_MOUSE_BUTTON */ DXFW_KEY_NONE,
  /* 0x05, XBUTTON1 */ DXFW_KEY_NONE,
  /* 0x06, XBUTTON2 */ DXFW_KEY_NONE,
  /* 0x07, Unassigned */ DXFW_KEY_NONE,
  /* 0x08, BACKSPACE */ DXFW_KEY_BACKSPACE,
  /* 0x09, TAB */ DXFW_KEY_TAB,
  /* 0x0A, Reserved */ DXFW_KEY_NONE,
  /* 0x0B, Reserved */ DXFW_KEY_NONE,
  /* 0x0C, CLEAR */ DXFW_KEY_NONE,
  /* 0x0D, RETURN */ DXFW_KEY_ENTER,
  /* 0x0E, ??? */ DXFW_KEY_NONE,
  /* 0x0F, ??? */ DXFW_KEY_NONE,
  /* 0x10, SHIFT */ DXFW_KEY_LSHIFT,
  /* 0x11, CONTROL */ DXFW_KEY_LCTRL,
  /* 0x12, MENU */ DXFW_KEY_ALT,
  /* 0x13, PAUSE */ DXFW_KEY_PAUSE,
  /* 0x14, CAPS_LOCK */ DXFW_KEY_CAPSLOCK,
  /* 0x15, KANA / HANGEUL / HANGUL  */ DXFW_KEY_NONE,
  /* 0x16, ??? */ DXFW_KEY_NONE,
  /* 0x17, JUNJA */ DXFW_KEY_NONE,
  /* 0x18, FINAL */ DXFW_KEY_NONE,
  /* 0x19, HANJA / KANJI */ DXFW_KEY_NONE,
  /* 0x1A, ??? */ DXFW_KEY_NONE,
  /* 0x1B, ESCAPE */ DXFW_KEY_ESCAPE,
  /* 0x1C, CONVERT */ DXFW_KEY_NONE,
  /* 0x1D, NONCONVERT */ DXFW_KEY_NONE,
  /* 0x1E, ACCEPT */ DXFW_KEY_NONE,
  /* 0x1F, MODECHANGE */ DXFW_KEY_NONE,
  /* 0x20, SPACE */ DXFW_KEY_SPACE,
  /* 0x21, PAGE_UP */ DXFW_KEY_PGDN,
  /* 0x22, PAGE_DOWN  */ DXFW_KEY_PGUP,
  /* 0x23, END */ DXFW_KEY_END,
  /* 0x24, HOME */ DXFW_KEY_HOME,
  /* 0x25, ARROW_LEFT */ DXFW_KEY_LEFT,
  /* 0x26, ARROW_UP */ DXFW_KEY_UP,
  /* 0x27, ARROW_RIGHT */ DXFW_KEY_RIGHT,
  /* 0x28, ARROW_DOWN */ DXFW_KEY_DOWN,
  /* 0x29, SELECT */ DXFW_KEY_NONE,
  /* 0x2A, PRINT */ DXFW_KEY_NONE,
  /* 0x2B, EXECUTE */ DXFW_KEY_NONE,
  /* 0x2C, PRINT_SCREEN */ DXFW_KEY_PRINTSCREEN,
  /* 0x2D, INSERT */ DXFW_KEY_INSERT,
  /* 0x2E, DELETE */ DXFW_KEY_DELETE,
  /* 0x2F, HELP */ DXFW_KEY_NONE,
  /* 0x30, NUMBER_0 */ DXFW_KEY_0,
  /* 0x31, NUMBER_1 */ DXFW_KEY_1,
  /* 0x32, NUMBER_2 */ DXFW_KEY_2,
  /* 0x33, NUMBER_3 */ DXFW_KEY_3,
  /* 0x34, NUMBER_4 */ DXFW_KEY_4,
  /* 0x35, NUMBER_5 */ DXFW_KEY_5,
  /* 0x36, NUMBER_6 */ DXFW_KEY_6,
  /* 0x37, NUMBER_7 */ DXFW_KEY_7,
  /* 0x38, NUMBER_8 */ DXFW_KEY_8,
  /* 0x39, NUMBER_9 */ DXFW_KEY_9,
  /* 0x3A, Unassigned */ DXFW_KEY_NONE,
  /* 0x3B, Unassigned */ DXFW_KEY_NONE,
  /* 0x3C, Unassigned */ DXFW_KEY_NONE,
  /* 0x3D, Unassigned */ DXFW_KEY_NONE,
  /* 0x3E, Unassigned */ DXFW_KEY_NONE,
  /* 0x3F, Unassigned */ DXFW_KEY_NONE,
  /* 0x40, Unassigned */ DXFW_KEY_NONE,
  /* 0x41, A */ DXFW_KEY_A,
  /* 0x42, B */ DXFW_KEY_B,
  /* 0x43, C */ DXFW_KEY_C,
  /* 0x44, D */ DXFW_KEY_D,
  /* 0x45, E */ DXFW_KEY_E,
  /* 0x46, F */ DXFW_KEY_F,
  /* 0x47, G */ DXFW_KEY_G,
  /* 0x48, H */ DXFW_KEY_H,
  /* 0x49, I */ DXFW_KEY_I,
  /* 0x4A, J */ DXFW_KEY_J,
  /* 0x4B, K */ DXFW_KEY_K,
  /* 0x4C, L */ DXFW_KEY_L,
  /* 0x4D, M */ DXFW_KEY_M,
  /* 0x4E, N */ DXFW_KEY_N,
  /* 0x4F, O */ DXFW_KEY_O,
  /* 0x50, P */ DXFW_KEY_P,
  /* 0x51, Q */ DXFW_KEY_Q,
  /* 0x52, R */ DXFW_KEY_R,
  /* 0x53, S */ DXFW_KEY_S,
  /* 0x54, T */ DXFW_KEY_T,
  /* 0x55, U */ DXFW_KEY_U,
  /* 0x56, V */ DXFW_KEY_V,
  /* 0x57, W */ DXFW_KEY_W,
  /* 0x58, X */ DXFW_KEY_X,
  /* 0x59, Y */ DXFW_KEY_Y,
  /* 0x5A, Z */ DXFW_KEY_Z,
  /* 0x5B, LEFT_WINDOWS */ DXFW_KEY_LWIN,
  /* 0x5C, RIGHT_WINDOWS */ DXFW_KEY_RWIN,
  /* 0x5D, APPLICATIONSS */ DXFW_KEY_NONE,
  /* 0x5E, Reserved */ DXFW_KEY_NONE,
  /* 0x5F, SLEEP */ DXFW_KEY_NONE,
  /* 0x60, NUMPAD0 */ DXFW_KEY_NUMPAD_0,
  /* 0x61, NUMPAD1 */ DXFW_KEY_NUMPAD_1,
  /* 0x62, NUMPAD2 */ DXFW_KEY_NUMPAD_2,
  /* 0x63, NUMPAD3 */ DXFW_KEY_NUMPAD_3,
  /* 0x64, NUMPAD4 */ DXFW_KEY_NUMPAD_4,
  /* 0x65, NUMPAD5 */ DXFW_KEY_NUMPAD_5,
  /* 0x66, NUMPAD6 */ DXFW_KEY_NUMPAD_6,
  /* 0x67, NUMPAD7 */ DXFW_KEY_NUMPAD_7,
  /* 0x68, NUMPAD8 */ DXFW_KEY_NUMPAD_8,
  /* 0x69, NUMPAD9 */ DXFW_KEY_NUMPAD_9,
  /* 0x6A, MULTIPLY */ DXFW_KEY_NUMPAD_ASTERISK,
  /* 0x6B, ADD */ DXFW_KEY_NUMPAD_ENTER,
  /* 0x6C, SEPARATOR */ DXFW_KEY_NUMPAD_SLASH,
  /* 0x6D, SUBTRACT */ DXFW_KEY_NUMPAD_MINUS,
  /* 0x6E, DECIMAL */ DXFW_KEY_NUMPAD_DECIMAL,
  /* 0x6F, DIVIDE */ DXFW_KEY_NUMPAD_SLASH,
  /* 0x70, F1 */ DXFW_KEY_F1,
  /* 0x71, F2 */ DXFW_KEY_F2,
  /* 0x72, F3 */ DXFW_KEY_F3,
  /* 0x73, F4 */ DXFW_KEY_F4,
  /* 0x74, F5 */ DXFW_KEY_F5,
  /* 0x75, F6 */ DXFW_KEY_F6,
  /* 0x76, F7 */ DXFW_KEY_F7,
  /* 0x77, F8 */ DXFW_KEY_F8,
  /* 0x78, F9 */ DXFW_KEY_F9,
  /* 0x79, F10 */ DXFW_KEY_F10,
  /* 0x7A, F11 */ DXFW_KEY_F11,
  /* 0x7B, F12 */ DXFW_KEY_F12,
  /* 0x7C, F13 */ DXFW_KEY_NONE,
  /* 0x7D, F14 */ DXFW_KEY_NONE,
  /* 0x7E, F15 */ DXFW_KEY_NONE,
  /* 0x7F, F16 */ DXFW_KEY_NONE,
  /* 0x80, F17 */ DXFW_KEY_NONE,
  /* 0x81, F18 */ DXFW_KEY_NONE,
  /* 0x82, F19 */ DXFW_KEY_NONE,
  /* 0x83, F20 */ DXFW_KEY_NONE,
  /* 0x84, F21 */ DXFW_KEY_NONE,
  /* 0x85, F22 */ DXFW_KEY_NONE,
  /* 0x86, F23 */ DXFW_KEY_NONE,
  /* 0x87, F24 */ DXFW_KEY_NONE,
  /* 0x88, Unassigned */ DXFW_KEY_NONE,
  /* 0x89, Unassigned */ DXFW_KEY_NONE,
  /* 0x8A, Unassigned */ DXFW_KEY_NONE,
  /* 0x8B, Unassigned */ DXFW_KEY_NONE,
  /* 0x8C, Unassigned */ DXFW_KEY_NONE,
  /* 0x8D, Unassigned */ DXFW_KEY_NONE,
  /* 0x8E, Unassigned */ DXFW_KEY_NONE,
  /* 0x8F, Unassigned */ DXFW_KEY_NONE,
  /* 0x90, NUMLOCK */ DXFW_KEY_NUMLOCK,
  /* 0x91, SCROLL */ DXFW_KEY_SCROLLLOCK,
  /* 0x92, OEM_NEC_EQUAL / OEM_FJ_JISHO */ DXFW_KEY_NONE,
  /* 0x93, OEM_FJ_MASSHOU */ DXFW_KEY_NONE,
  /* 0x94, OEM_FJ_TOUROKU */ DXFW_KEY_NONE,
  /* 0x95, OEM_FJ_LOYA */ DXFW_KEY_NONE,
  /* 0x96, OEM_FJ_ROYA */ DXFW_KEY_NONE,
  /* 0x97, Unassigned */ DXFW_KEY_NONE,
  /* 0x98, Unassigned */ DXFW_KEY_NONE,
  /* 0x99, Unassigned */ DXFW_KEY_NONE,
  /* 0x9A, Unassigned */ DXFW_KEY_NONE,
  /* 0x9B, Unassigned */ DXFW_KEY_NONE,
  /* 0x9C, Unassigned */ DXFW_KEY_NONE,
  /* 0x9D, Unassigned */ DXFW_KEY_NONE,
  /* 0x9E, Unassigned */ DXFW_KEY_NONE,
  /* 0x9F, Unassigned */ DXFW_KEY_NONE,
  /* 0xA0, LSHIFT */ DXFW_KEY_LSHIFT,
  /* 0xA1, RSHIFT */ DXFW_KEY_RSHIFT,
  /* 0xA2, LCONTROL */ DXFW_KEY_LCTRL,
  /* 0xA3, RCONTROL */ DXFW_KEY_RCTRL,
  /* 0xA4, LMENU */ DXFW_KEY_ALT,
  /* 0xA5, RMENU */ DXFW_KEY_ALT,
  /* 0xA6, BROWSER_BACK */ DXFW_KEY_NONE,
  /* 0xA7, BROWSER_FORWARD */ DXFW_KEY_NONE,
  /* 0xA8, BROWSER_REFRESH */ DXFW_KEY_NONE,
  /* 0xA9, BROWSER_STOP */ DXFW_KEY_NONE,
  /* 0xAA, BROWSER_SEARCH */ DXFW_KEY_NONE,
  /* 0xAB, BROWSER_FAVORITES */ DXFW_KEY_NONE,
  /* 0xAC, BROWSER_HOME */ DXFW_KEY_NONE,
  /* 0xAD, VOLUME_MUTE */ DXFW_KEY_NONE,
  /* 0xAE, VOLUME_DOWN */ DXFW_KEY_NONE,
  /* 0xAF, VOLUME_UP */ DXFW_KEY_NONE,
  /* 0xB0, MEDIA_NEXT_TRACK */ DXFW_KEY_NONE,
  /* 0xB1, MEDIA_PREV_TRACK */ DXFW_KEY_NONE,
  /* 0xB2, MEDIA_STOP */ DXFW_KEY_NONE,
  /* 0xB3, MEDIA_PLAY_PAUSE */ DXFW_KEY_NONE,
  /* 0xB4, LAUNCH_MAIL */ DXFW_KEY_NONE,
  /* 0xB5, LAUNCH_MEDIA_SELECT */ DXFW_KEY_NONE,
  /* 0xB6, LAUNCH_APP1 */ DXFW_KEY_NONE,
  /* 0xB7, LAUNCH_APP2 */ DXFW_KEY_NONE,
  /* 0xB8, Reserved */ DXFW_KEY_NONE,
  /* 0xB9, Reserved */ DXFW_KEY_NONE,
  /* 0xBA, OEM_1, ';:' for US */ DXFW_KEY_SEMICOLON,
  /* 0xBB, OEM_PLUS, '+' any country */ DXFW_KEY_EQUALS,
  /* 0xBC, OEM_COMMA, ',' any country */ DXFW_KEY_COMMA,
  /* 0xBD, OEM_MINUS, '-' any country */ DXFW_KEY_MINUS,
  /* 0xBE, OEM_PERIOD, '.' any country */ DXFW_KEY_DOT,
  /* 0xBF, OEM_2, '/?' for US */ DXFW_KEY_SLASH,
  /* 0xC0, OEM_3, '`~' for US */ DXFW_KEY_TILDE,
  /* 0xC1, Reserved */ DXFW_KEY_NONE,
  /* 0xC2, Reserved */ DXFW_KEY_NONE,
  /* 0xC3, Reserved */ DXFW_KEY_NONE,
  /* 0xC4, Reserved */ DXFW_KEY_NONE,
  /* 0xC5, Reserved */ DXFW_KEY_NONE,
  /* 0xC6, Reserved */ DXFW_KEY_NONE,
  /* 0xC7, Reserved */ DXFW_KEY_NONE,
  /* 0xC8, Reserved */ DXFW_KEY_NONE,
  /* 0xC9, Reserved */ DXFW_KEY_NONE,
  /* 0xCA, Reserved */ DXFW_KEY_NONE,
  /* 0xCB, Reserved */ DXFW_KEY_NONE,
  /* 0xCC, Reserved */ DXFW_KEY_NONE,
  /* 0xCD, Reserved */ DXFW_KEY_NONE,
  /* 0xCE, Reserved */ DXFW_KEY_NONE,
  /* 0xCF, Reserved */ DXFW_KEY_NONE,
  /* 0xD0, Reserved */ DXFW_KEY_NONE,
  /* 0xD1, Reserved */ DXFW_KEY_NONE,
  /* 0xD2, Reserved */ DXFW_KEY_NONE,
  /* 0xD3, Reserved */ DXFW_KEY_NONE,
  /* 0xD4, Reserved */ DXFW_KEY_NONE,
  /* 0xD5, Reserved */ DXFW_KEY_NONE,
  /* 0xD6, Reserved */ DXFW_KEY_NONE,
  /* 0xD7, Reserved */ DXFW_KEY_NONE,
  /* 0xD8, Unassigned */ DXFW_KEY_NONE,
  /* 0xD9, Unassigned */ DXFW_KEY_NONE,
  /* 0xDA, Unassigned */ DXFW_KEY_NONE,
  /* 0xDB, OEM_4, '[{' for US */ DXFW_KEY_OPENBRACE,
  /* 0xDC, OEM_5, '\|' for US */ DXFW_KEY_BACKSLASH,
  /* 0xDD, OEM_6, ']}' for US */ DXFW_KEY_CLOSEBRACE,
  /* 0xDE, OEM_7, ''"' for US */ DXFW_KEY_QUOTE,
  /* 0xDF, OEM_8 */ DXFW_KEY_NONE,
  /* 0xE0, Reserved */ DXFW_KEY_NONE,
  /* 0xE1, OEM_AX, 'AX' key on Japanese AX kbd */ DXFW_KEY_NONE,
  /* 0xE2, OEM_102, "<>" or "\|" on RT 102-key kbd. */ DXFW_KEY_NONE,
  /* 0xE3, ICO_HELP, Help key on ICO */ DXFW_KEY_NONE,
  /* 0xE4, ICO_00, 00 key on ICO */ DXFW_KEY_NONE,
  /* 0xE5, PROCESSKEY */ DXFW_KEY_NONE,
  /* 0xE6, ICO_CLEAR */ DXFW_KEY_NONE,
  /* 0xE7, PACKET */ DXFW_KEY_NONE,
  /* 0xE8, Unassigned */ DXFW_KEY_NONE,
  /* 0xE9, OEM_RESET */ DXFW_KEY_NONE,
  /* 0xEA, OEM_JUMP */ DXFW_KEY_NONE,
  /* 0xEB, OEM_PA1 */ DXFW_KEY_NONE,
  /* 0xEC, OEM_PA2 */ DXFW_KEY_NONE,
  /* 0xED, OEM_PA3 */ DXFW_KEY_NONE,
  /* 0xEE, OEM_WSCTRL */ DXFW_KEY_NONE,
  /* 0xEF, OEM_CUSEL */ DXFW_KEY_NONE,
  /* 0xF0, OEM_ATTN */ DXFW_KEY_NONE,
  /* 0xF1, OEM_FINISH */ DXFW_KEY_NONE,
  /* 0xF2, OEM_COPY */ DXFW_KEY_NONE,
  /* 0xF3, OEM_AUTO */ DXFW_KEY_NONE,
  /* 0xF4, OEM_ENLW */ DXFW_KEY_NONE,
  /* 0xF5, OEM_BACKTAB */ DXFW_KEY_NONE,
  /* 0xF6, ATTN */ DXFW_KEY_NONE,
  /* 0xF7, CRSEL */ DXFW_KEY_NONE,
  /* 0xF8, EXSEL */ DXFW_KEY_NONE,
  /* 0xF9, EREOF */ DXFW_KEY_NONE,
  /* 0xFA, PLAY */ DXFW_KEY_NONE,
  /* 0xFB, ZOOM */ DXFW_KEY_NONE,
  /* 0xFC, NONAME */ DXFW_KEY_NONE,
  /* 0xFD, PA1 */ DXFW_KEY_NONE,
  /* 0xFE, OEM_CLEAR */ DXFW_KEY_NONE,
  /* 0xFF, Reserved */ DXFW_KEY_NONE,
};

/* GLOBAL KEYBOARD STATE */
dxfwVirtualKeyState g_keyboard_state_[DXFW_KEY_COUNT] = { DXFW_KEY_STATE_UP };
dxfwVirtualKeyState g_keyboard_previous_state_[DXFW_KEY_COUNT] = { DXFW_KEY_STATE_UP };

/* KEYBOARD FUNCTIONS */
dxfwVirtualKeyCode dxfwGetKeyCode(USHORT windows_key_code) {
  return g_windows_to_virtual_key_code_[windows_key_code];
}

void dxfwRegisterKeyDown(dxfwVirtualKeyCode key_code) {
  g_keyboard_previous_state_[key_code] = g_keyboard_state_[key_code];
  g_keyboard_state_[key_code] = DXFW_KEY_STATE_DOWN;
}

void dxfwRegisterKeyUp(dxfwVirtualKeyCode key_code) {
  g_keyboard_previous_state_[key_code] = g_keyboard_state_[key_code];
  g_keyboard_state_[key_code] = DXFW_KEY_STATE_UP;
}

dxfwVirtualKeyState dxfwGetKeyState(dxfwVirtualKeyCode key_code) {
  return g_keyboard_state_[key_code];
}

dxfwVirtualKeyState dxfwGetPreviousKeyState(dxfwVirtualKeyCode key_code) {
  return g_keyboard_previous_state_[key_code];
}

dxfwVirtualKeyModifiers dxfwGetModifierFlags() {
  int32_t modifier_flags = DXFW_KEY_MODIFIER_NONE;
  modifier_flags |= (g_keyboard_state_[DXFW_KEY_LSHIFT] * DXFW_KEY_MODIFIER_SHIFT);
  modifier_flags |= (g_keyboard_state_[DXFW_KEY_RSHIFT] * DXFW_KEY_MODIFIER_SHIFT);
  modifier_flags |= (g_keyboard_state_[DXFW_KEY_LCTRL] * DXFW_KEY_MODIFIER_CTRL);
  modifier_flags |= (g_keyboard_state_[DXFW_KEY_RCTRL] * DXFW_KEY_MODIFIER_CTRL);
  modifier_flags |= (g_keyboard_state_[DXFW_KEY_ALT] * DXFW_KEY_MODIFIER_ALT);
  modifier_flags |= (g_keyboard_state_[DXFW_KEY_LWIN] * DXFW_KEY_MODIFIER_LWIN);
  modifier_flags |= (g_keyboard_state_[DXFW_KEY_RWIN] * DXFW_KEY_MODIFIER_RWIN);

  return (dxfwVirtualKeyModifiers)modifier_flags;
}
